version: '3'
services:
  elastic:
    image: elasticsearch:6.6.2
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:6.6.2
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://172.17.0.1:9200